### ISSUE TITLE
WISH: Set up a ROADMAP

### ISSUE THREAD

**Issue by TisonKun** [red/docs#27]
Right now our documentation is written casually and a bit messy. IMO it's worth to set up a ROADMAP how we document Red. So I leave this issue as an entry.

How about, firstly, follow the structure like (http://www.rebol.com/docs/core23/rebolcore.html) and build an overviews of Red Core.

**Comment by greggirwin** [comment]
Noted, thanks. We have a lot of things we hope to improve in docs.

**Comment by ifmihai** [comment]
I'm a new comer to red. Found it some month ago. I love the concept, but documentation "a bit messy" is an understatement. 
I kinda put red on hold because of it. 
Thinking "let's wait for 1.0 or something" 

Just giving newbie feedback. 

Ps. 
I understood rebol2 is closest. 
I guess i will continue with their docs

**Comment by PeterWAWood** [comment]
https://github.com/red/REP/blob/master/REPs/rep-0003.adoc
